# Generated by Django 4.2.7 on 2024-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('P', 'Printer'), ('D', 'Design'), ('M', 'Material'), ('I', 'Impression')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('show', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('imageRoute', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
