# Generated by Django 5.0.2 on 2024-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_imageroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainPage',
            field=models.BooleanField(default=True),
        ),
    ]
