# Generated by Django 5.0.2 on 2024-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_imageroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.FileField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
