# Generated by Django 5.0.2 on 2024-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_mainpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mainPage',
        ),
        migrations.AlterField(
            model_name='product',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
