# Generated by Django 5.0.2 on 2024-03-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_design'),
        ('products', '0007_remove_product_mainpage_alter_product_show'),
    ]

    operations = [
    ]
