# Generated by Django 5.0.2 on 2024-04-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_yer_mail_order_buyer_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Enviado', 'Enviado'), ('En reparto', 'En reparto')], default='Pendiente', max_length=10),
        ),
    ]
