# Generated by Django 5.0.2 on 2024-04-11 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderactiontoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderactiontoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 14, 10, 6, 676402, tzinfo=datetime.timezone.utc)),
        ),
    ]
