# Generated by Django 4.1.13 on 2024-04-15 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_orderactiontoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderactiontoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 13, 43, 49, 729850, tzinfo=datetime.timezone.utc)),
        ),
    ]
