# Generated by Django 5.0.2 on 2024-04-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='imageRoute',
            field=models.CharField(default='', max_length=100),
        ),
    ]
