# Generated by Django 5.0.2 on 2024-04-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_image_report_imageroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='imageRoute',
        ),
    ]
