# Generated by Django 5.0.2 on 2024-03-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageRoute',
        ),
    ]
