# Generated by Django 4.2.7 on 2024-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Juan', max_length=50),
        ),
    ]
