# Generated by Django 5.0.2 on 2024-03-09 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(52999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
