# Generated by Django 5.0.2 on 2024-03-12 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(52999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
