# Generated by Django 5.0.2 on 2024-03-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_postal_code'),
        ('users', '0007_customuser_profile_picture_and_more'),
    ]

    operations = [
    ]
