# Generated by Django 5.0.2 on 2024-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20240312_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
