# Generated by Django 5.0.2 on 2024-03-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_followers_customuser_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
