# Generated by Django 4.2.7 on 2024-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdesign',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='customdesign',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customdesign',
            name='width',
        ),
        migrations.AddField(
            model_name='customdesign',
            name='dimensions',
            field=models.JSONField(default=dict),
        ),
    ]
