# Generated by Django 4.2.7 on 2024-02-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0002_remove_customdesign_depth_remove_customdesign_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customdesign',
            old_name='design_id',
            new_name='custom_design_id',
        ),
    ]
