# Generated by Django 4.2.7 on 2024-02-24 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_design', '0003_rename_design_id_customdesign_custom_design_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdesign',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='city',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='postal_code',
            field=models.CharField(default='41720', max_length=5),
        ),
    ]
