# Generated by Django 4.2.7 on 2024-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0005_customdesign_buyer_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdesign',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
