# Generated by Django 5.0.2 on 2024-03-13 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0006_customdesign_payed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customdesign',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Impresor asignado al diseño', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customdesign',
            name='status',
            field=models.CharField(choices=[('searching', 'Buscando impresor'), ('printing', 'Imprimiendo'), ('printed', 'Impreso')], default='searching', help_text='Estado del diseño personalizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='customdesign',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_designs', to=settings.AUTH_USER_MODEL),
        ),
    ]
