# Generated by Django 4.1.13 on 2024-03-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0007_customdesign_color_customdesign_printer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdesign',
            name='custom_design_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
